services:
  website:
    image: ghcr.io/huskynz/10:${IMAGE_TAG}
    container_name: huskynz_msite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
    env_file: .env

    #environment:
    #  - GITHUB_TOKEN=${GITHUB_TOKEN}
    #  - GITHUB_USERNAME=${GITHUB_USERNAME}
      #- RESEND_API_KEY=${RESEND_API_KEY}
      #- CONTACT_SEND_EMAIL=${CONTACT_SEND_EMAIL}
      #- CONTACT_EMAIL=${CONTACT_EMAIL}
      #- PUBLIC_TURNSTILE_SITE_KEY=${PUBLIC_TURNSTILE_SITE_KEY}
      #- TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      #- TWITCH_CHANNEL=${TWITCH_CHANNEL}
      #- TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      #- TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      #- PRODUCTION_DOMAIN=${PRODUCTION_DOMAIN}
      #- AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      #- AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      #- AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

  
