name: Clean up old packages

on:
  push:
    tags:
      - 'cr*'
    branches:
      - 'master'
      - 'dev'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:      # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ github.repository }}
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: false
          ignore-versions: |
            master
            dev
            cr*
          token: ${{ github.token }}
